version: 2
jobs:
  build:
    docker:
      - image: cimg/node:current

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
          - v1-dependencies-

      - run:
          name: Install Dependencies
          command: yarn

      - save_cache:
          paths: node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}

      - run:
          name: Build App
          command: yarn build

      - run:
          name: Create SA key JSON
          command: echo $GOOGLE_APPLICATION_CREDENTIALS > "$HOME"/gcloud.json

      - run:
          name: Deploy to Firebase
          command: GOOGLE_APPLICATION_CREDENTIALS="$HOME"/gcloud.json yarn deploy