version: 2
jobs:
  build:
    docker:
      - image: cimg/node:current
    working_directory: ~/footprints

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
          - v1-dependencies-

      - run:
          name: Setup Environment
          command: echo 'export PATH=${PATH}:${HOME}/footprints/node_modules/.bin' >> $BASH_ENV

      - run:
          name: Install Dependencies
          command: yarn

      - save_cache:
          paths: node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}

      - run:
          name: Run Unit Tests
          command: yarn test

      - run:
          name: Build App
          command: yarn build

      - run:
          name: Deploy to Firebase
          command: yarn deploy